language: ruby
script: bundle exec rake
bundler_args: --without perf
cache: bundler

rvm:
  - 1.9.3
  - 2.0.0-p648
  - 2.1.10
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head
  - ree
  - jruby-18mode
  - jruby-19mode
  - jruby-head

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ree
    - rvm: ruby-head
    - rvm: jruby-head
  include:
    - rvm: 1.8.7
      dist: precise
    - rvm: 1.9.2
      dist: trusty
